# Generated by Django 5.2.7 on 2025-11-05 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                ("uuid", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("platform", models.CharField(choices=[("TELEGRAM", "Telegram")], max_length=255)),
                ("platform_chat_id", models.CharField(max_length=255)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("username", models.CharField(blank=True, max_length=255, null=True)),
                ("first_name", models.CharField(blank=True, max_length=255, null=True)),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
                ("language_code", models.CharField(blank=True, max_length=2, null=True)),
                ("additional_info", models.JSONField(blank=True, null=True)),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                ("uuid", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_id", models.CharField(max_length=255, unique=True)),
                ("short_name", models.CharField(max_length=255)),
                ("full_name", models.CharField(max_length=1024)),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
                "indexes": [
                    models.Index(fields=["uuid", "external_id"], name="main_depart_uuid_f985a9_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                ("uuid", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("short_name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
                "indexes": [
                    models.Index(fields=["uuid", "short_name"], name="main_facult_uuid_474f90_idx"),
                    models.Index(fields=["short_name"], name="main_facult_short_n_d40090_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                ("uuid", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("short_name", models.CharField(max_length=255)),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="main.faculty",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MessageCampaign",
            fields=[
                ("uuid", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=512)),
                ("payload", models.JSONField()),
                (
                    "recipients",
                    models.ManyToManyField(
                        blank=True, related_name="message_campaigns_m2m", to="main.chat"
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("uuid", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True, related_name="subscriptions", to="main.group"
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="chat",
            name="subscription",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat",
                to="main.subscription",
            ),
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                ("uuid", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_id", models.CharField(max_length=255, unique=True)),
                ("short_name", models.CharField(max_length=255)),
                ("full_name", models.CharField(max_length=1024)),
                (
                    "departments",
                    models.ManyToManyField(
                        blank=True, related_name="teachers_m2m", to="main.department"
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="subscription",
            name="teachers",
            field=models.ManyToManyField(
                blank=True, related_name="subscriptions", to="main.teacher"
            ),
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(fields=["uuid", "short_name"], name="main_group_uuid_1be764_idx"),
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(fields=["short_name"], name="main_group_short_n_e64ae4_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="group",
            unique_together={("short_name", "faculty")},
        ),
        migrations.AlterUniqueTogether(
            name="chat",
            unique_together={("platform", "platform_chat_id")},
        ),
        migrations.AddIndex(
            model_name="teacher",
            index=models.Index(fields=["uuid", "external_id"], name="main_teache_uuid_9d451c_idx"),
        ),
    ]
