# Generated by Django 5.2.7 on 2025-11-05 16:58

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("f2c1f4c0-f174-4e51-ab0d-4f712c0bcaca"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("f2c1f4c0-f174-4e51-ab0d-4f712c0bcaca"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("f2c1f4c0-f174-4e51-ab0d-4f712c0bcaca"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("f2c1f4c0-f174-4e51-ab0d-4f712c0bcaca"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="messagecampaign",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("f2c1f4c0-f174-4e51-ab0d-4f712c0bcaca"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("f2c1f4c0-f174-4e51-ab0d-4f712c0bcaca"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("f2c1f4c0-f174-4e51-ab0d-4f712c0bcaca"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
