# Generated by Django 5.2.13 on 2026-04-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_chat_main_chat_platfor_451de3_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="faculty",
            name="parent_prefix",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
