# Generated by Django 5.2.13 on 2026-04-18 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_faculty_parent_prefix"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faculty",
            name="parent_prefix",
        ),
        migrations.AddField(
            model_name="faculty",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="main.faculty",
            ),
        ),
    ]
