# Generated by Django 4.1.6 on 2023-07-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScheduleCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("faculty", models.CharField(max_length=100)),
                ("group", models.CharField(max_length=100)),
                ("schedule", models.JSONField()),
                ("at_time", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
